### ISSUE TITLE
Export file type option not specified

### ISSUE THREAD

**Issue by AliElHabti** [HitmanHimself/GOWTool#5]
I've followed all the steps and have ended up with this:
![image](https://user-images.githubusercontent.com/95886705/182455437-5e398fb7-a16d-41f6-a840-bd4415c73bf4.png)
 What do I do next?

**Comment by Claw256** [comment]
I got my export of texpacks to DDS files working by using this command:
```
.\GOWTool.exe texpack --path "C:\Users\Rexami\GOWExtracted\main.texpack" --outpath "C:\Users\Rexami\GOWExtracted\Output\Textures" --export --dds
```

**Comment by lllllllll6321** [comment]
> I've followed all the steps and have ended up with this: ![image](https://user-images.githubusercontent.com/95886705/182455437-5e398fb7-a16d-41f6-a840-bd4415c73bf4.png) What do I do next?

You are missing the flags. The little "chart" at the bottom is showing the available flags (as well as what they do). However, it's definitely a learning curve. So essentially, your command should look something like this:

**[GOWTool.exe Directory] -p ["Specific File path"] -o ["Output File folder path"] -t -d -m**
