### ISSUE TITLE
request update to support GOW Ragnarok WAD

### ISSUE THREAD

**Issue by BanhMi939** [HitmanHimself/GOWTool#7]
like the title said, please update the tool to support export and import new WAD file from GOW Ragnarok. Here are some sample.
[wad.zip](https://github.com/HitmanHimself/GOWTool/files/9978193/wad.zip)

**Comment by kotn3l** [comment]
I second this.

**Comment by kainotoa** [comment]
a847c5fe6bab04b56e8b657b9d9f54ccd36a72bc
