### ISSUE TITLE
Models exporting with only one "Default" material

### ISSUE THREAD

**Issue by LokiVig** [HitmanHimself/GOWTool#9]
I've been wanting to port these models to Source 2, just for shits and giggles, but the models always only have one material named "Default", is this a known and fixable issue?

![bild](https://user-images.githubusercontent.com/87585550/206458724-95c06a5e-689c-4cf2-be7c-267514877db7.png)
Image is of Freya in Blender, showing the only existing material

**Comment by kainotoa** [comment]
materials are not supported
